# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_categoria_options_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(choices=[('pedido', 'Un pedido'), ('producto', 'Un producto'), ('otro', 'Otra consulta')], default='otro', max_length=20)),
                ('numero_pedido', models.CharField(blank=True, help_text='Lo encontrarás en el email de confirmación.', max_length=20, verbose_name='número de pedido')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False, verbose_name='leído')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
